### PR TITLE
adds timeout option to HTTP client. Closes #27

### LINKED ISSUE #27: Call to CloudBees will hang forever if the service is down
According to [Guzzle docs](https://docs.guzzlephp.org/en/stable/request-options.html#timeout), the default timeout is 0, which will wait indefinitely for the response.
Since it seems no timeout is being set [here](https://github.com/rollout/rox-php/blob/1df28e29022e91951096b8da80cc6281926fabec/src/Rox/Core/Network/GuzzleHttpClient.php#L60), in case CloudBees call times out, the caller will hang forever instead of assuming the default value.

### PR DESCRIPTION
**Pull request by leobeal-cpi**

### CODE REVIEW

**Review by horiaconstantin-cpi — APPROVED** [review]
Could someone take a look at this and merge it soon?

**Comment by AsafRollout** [comment]
thank you for submitting this improvement!
we will discuss it internally and proceed as soon as we agree

**Comment by leobeal-cpi** [comment]
Thanks for your feedback @AsafRollout.
We have a small service stuck in an old php version. 
If you want I can also open a PR against the v5

**Comment by AsafRollout** [comment]
@leobeal-cpi 
yes, it seems that we prefer not to update an old version unless you strongly prefer we will do so...

if you can do it to the latest version it will be awesome (and will be merged ASAP)
we can also apply these changes to the latest version ourselves if you prefer (probably next week)

**Comment by AsafRollout** [comment]
oh, it is a merge request to master 
sorry for making you create the other PR 😞

**Comment by AsafRollout** [comment]
@leobeal-cpi 
i'm closing this PR
5.0.1 and 4.8.1 were released with the setTimeout addition

**Comment by leobeal-cpi** [comment]
Thanks for that @AsafRollout. Specially for the 4.8.x 🥇 

Please bear in mind that the default is still 0 (no timeout). Could you please make sure the documentation is updated to reflect the new changes and ideally stress that a timeout must be set?

Thanks one more time!

**Pull request closed without merging**
